services:
  db:
    image: postgres:latest
    container_name: friendship_plus_db
    environment:
      POSTGRES_DB: friendship_plus
      POSTGRES_USER: fsplus
      POSTGRES_PASSWORD: group6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
